### PR TITLE
Log instead of error

### PR DESCRIPTION
**Pull request by strubium**
Does not need to be a error.

### CODE REVIEW

**Comment by theendercore** [comment]
This is an intentional choice on my part.

**Comment by strubium** [comment]
Your choice is intentionally stupid (on your part)

**Comment by theendercore** [comment]
That's a subjective opinion.

**Comment by strubium** [comment]
i find this very funny 
https://github.com/theendercore/NarrusYeetus/commit/d4a79285be1cdddda3612d6fb56747ffa8f6b53c

**Comment by theendercore** [comment]
Yeah I have no idea why i had such a string opinion about this a year ago.

**Pull request closed without merging**
